### PR TITLE
Create/update pdf schema

### PR DESCRIPTION
**Pull request by pharmaguide**

### CODE REVIEW

**Comment by travist** [comment]
Thanks for this and sorry about the late response. I will set some time aside this weekend to test this out and give you feedback and maybe commit it. This is an amazing contribution!

**Comment by pharmaguide** [comment]
Thanks Travis. 

Looking forward to your response. 

Regards 

-- 
Walid Mowaswes
CEO
PharmaGuide
m:	(647) 221-7547
a:	55 West Beaver Creek Road Unit 20
w:	pharmaguide.ca e: walid@pharmaguide.ca

**Comment by travist** [comment]
Hello @pharmaguide,

I wanted to let you know that this is still high on my list of things to accomplish, but we had a few things early this week that took longer than I expected. I am hoping to get to this either tomorrow or maybe over the weekend.

Thanks for your patience. I am really excited about this addition to our CLI tool.

**Comment by travist** [comment]
So I had some time to look into this. I also took the liberty to make some changes to allow for the create form to start working (it seemed to be broken).

Here is what it ends up creating as far as fields are concerned.

Alt text

So, it looks like it is not scaling the field positions correctly, but it does appear to be getting most of them. It also looks like it is merging two separate pages into a single page which is also a problem.

It is getting really close, but still needs some work.

Thanks!

Travis.

**Comment by travist** [comment]
I am going to merge this in, and we will make comments to the existing PR.

**Pull request merged**
